[build]
  publish = "web"
  command = "npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
